### ISSUE TITLE
hardcoded paths

### ISSUE THREAD

**Issue by gerhardmack** [bmanojlovic/mod_authn_dovecot#4]
You have apxs2 hardcoded as /usr/sbin/apxs2 on debian it's /usr/bin/apxs2.

I also had the same problem with -I/usr/include/apr-1.  Again on Debian it's -I/usr/include/apr-1.0.

**Comment by bmanojlovic** [comment]
Hello @gerhardmack, I have just released code with autconf configure script which should work correctly on your system.
