### ISSUE TITLE
configure: cannot find input file: `Makefile.in'

### ISSUE THREAD

**Issue by ploink** [bmanojlovic/mod_authn_dovecot#7]
Running ./configure ends in:

_config.status: error: cannot find input file: `Makefile.in'_

**Comment by bmanojlovic** [comment]
provided Makefile is sufficient for building, configure is "not functional" as in not generating Makefile itself, but more as check of required software that should be installed on your system for building module itself. 
point is just run `make` in freshly cloned repository and that is it, if that does not work i will look into your specifics
